version: '3.8'

services:
  postgres:
    image: postgres
    container_name: container_db_caneco
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: db_caneco
    volumes:
      - meu_db_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

volumes:
  meu_db_data:
